select * from customer; 

--Q.1 What is the total revenue generated by male vs. female ?
select gender ,sum(purchase_amount)as revenue
from customer 
group by gender;

--Q.2 Which customer used a discount but still spent more than the average purchase amount ?
select discount_applied,purchase_amount
from customer
where discount_applied= 'Yes' and purchase_Amount>=(select avg(purchase_amount) from customer);

--Q.3 Which are the top 5 products with the highest average review rating?
select item_purchased ,  ROUND(AVG(review_rating)::numeric,2)  AS "Average Rewiew Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q.4 Compare the average Purchase Amount between Standard  and Express Shipping.
select shipping_type ,
round(avg(purchase_amount)::numeric,2)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q.5 Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non subscribers?
select subscription_status,
count(customer_id ) as total_customer,
round(avg(purchase_amount)::numeric,2) as avg_spend,
round(sum(purchase_amount)::numeric,2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc


--Q.6 Which 5 products have the highest percentage of purchase with discounts applied ?
select item_purchased,
round(sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*):: numeric ,2) * 100 as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

--Q.7 Segment customers into New ,Returning and Loyal based on their total number of purchases and show the count of each segment.
with customer_type as( 
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as Customer_segment
from customer 
)
select customer_segment , 
count(*) as  "Number of customers"
from customer_type
group by customer_segment
order by "Number of customers" desc

 

-- Q.8 What are the top 3 purchased products within each category ?
with item_counts as (
select item_purchased , category ,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category , item_purchased)

select item_purchased, category, item_rank,total_orders
from item_counts
where item_rank<=3;

--Q.9 Are customers who are repeated buyers (more than 5 previous purcahses )likely to subscribe ?
select subscription_status,
count(customer_id) as repeated_buyers 
from customer 
where previous_purchases >5
group by subscription_status ;

--Q.10 What is the revenue contribution of each age group ?
select age_group,
sum (purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc ;
